export {default as HeroContainer} from './hero-container'
export {default as BrandIntroContainer} from './brand-intro'
export {default as TrendingProducts} from './trending-products'
export {default as BrandStat} from './brand-customers-stat'
export {default as BrandFAQContainer} from './brand-faq'
export {default as Testimonials} from './testimonials'